image:
  file: .gitpod.dockerfile
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - eventyret.bootstrap-4-cdn-snippet
    - matt-rudge.auto-open-preview-panel
    - esbenp.prettier-vscode
    - CoenraadS.bracket-pair-colorizer
    - redwan-hossain.auto-rename-tag-clone
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
